# Generated by Django 4.2.4 on 2023-08-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
    ]
