# Generated by Django 4.2.4 on 2023-08-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_customuser_notification_projectproposal_projecttopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
    ]
