# Generated by Django 4.2.4 on 2023-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='register.userrole'),
        ),
    ]
