# Generated by Django 4.2.4 on 2023-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='student',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ProjectProposal',
        ),
        migrations.DeleteModel(
            name='ProjectTopic',
        ),
    ]
